apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudgrep-ingestor-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: cloudgrep-ingestor-secrets
  data:
    - secretKey: PORT
      remoteRef:
        key: DEV__INGESTOR__PORT
    - secretKey: REDIS_ADDR
      remoteRef:
        key: DEV__INGESTOR__REDIS_ADDR
    - secretKey: OPENSEARCH_ADDR
      remoteRef:
        key: DEV__INGESTOR__OPENSEARCH_ADDR
