apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudgrep-manager-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: cloudgrep-manager-secrets
  data:
    - secretKey: SERVER__PORT
      remoteRef:
        key: DEV__MANAGER__SERVER__PORT
    - secretKey: SERVER__ENVIRONMENT
      remoteRef:
        key: DEV__MANAGER__SERVER__ENVIRONMENT
    - secretKey: DATABASE__URI
      remoteRef:
        key: DEV__MANAGER__DATABASE__URI
    - secretKey: DATABASE__DATABASE
      remoteRef:
        key: DEV__MANAGER__DATABASE__DATABASE
    - secretKey: REDIS__ADDR
      remoteRef:
        key: DEV__MANAGER__REDIS__ADDR
    - secretKey: REDIS__USERNAME
      remoteRef:
        key: DEV__MANAGER__REDIS__USERNAME
    - secretKey: REDIS__PASSWORD
      remoteRef:
        key: DEV__MANAGER__REDIS__PASSWORD
    - secretKey: SCHEDULER__STRATEGY
      remoteRef:
        key: DEV__MANAGER__SCHEDULER__STRATEGY
    - secretKey: WORKER__HEARTBEAT_TIMEOUT_SECONDS
      remoteRef:
        key: DEV__MANAGER__WORKER__HEARTBEAT_TIMEOUT_SECONDS
    - secretKey: WORKER__CLEANUP_INTERVAL_SECONDS
      remoteRef:
        key: DEV__MANAGER__WORKER__CLEANUP_INTERVAL_SECONDS
